db:
  image: geographica/postgis:postgresql-9.3.5-postgis-2.1.7-gdal-1.11.2-Patched
  ports:
    - "5435:5432"

geoserver:
  image: geographica/geoserver:v2.6.2
  ports:
    - "8084:8080"
  links:
    - db

destinationgeoserver:
  image: geographica/geoserver:v2.6.2
  ports:
    - "8085:8080"
  links:
    - db
